### ISSUE TITLE
Text input field aligment

### ISSUE THREAD

**Issue by pioug** [kkga/spacegray#190]
Thank you @marcofugaro for maintaining this theme!

I notice since the last update that the text input fields in the bottom panel are not correctly aligned with the labels:
![image](https://cloud.githubusercontent.com/assets/3654180/20700243/20116894-b647-11e6-8202-febece4cba2e.png)

To fix the alignment, I set `content_margin: 9` instead of `3` here https://github.com/kkga/spacegray/blob/master/Spacegray.sublime-theme#L807.

But it looks like this line has not been touch since 2004 (https://github.com/kkga/spacegray/blame/master/Spacegray.sublime-theme#L807).

I would be glad to create a PR but I am not sure if I correctly identified the issue.

I am using ST3 on MBP (Retina display if it matters) with macOS 10.12.1. 
Here is Sublime settings:
```
{
	"color_scheme": "Packages/User/SublimeLinter/Otto Tomorrow (SL).tmTheme",
	"draw_minimap_border": false,
	"enable_tab_scrolling": false,
	"ensure_newline_at_eof_on_save": true,
	"folder_exclude_patterns":
	[
		".sass-cache",
		".tmp",
		".git",
		".nyc_output",
		"bower_components",
		"build",
		"docs",
		"dist",
		"node_modules"
	],
	"font_face": "DejaVu Sans Mono",
	"font_size": 10,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
	],
	"open_files_in_new_window": true,
	"scroll_past_end": true,
	"spacegray_tabs_font_small": true,
	"spell_check": false,
	"tab_size": 2,
	"theme": "Spacegray.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"word_wrap": true
}
```

**Comment by arinsoye** [comment]
Could you let me know how to make the same edit and apply it? I am interested in the same fix. If possible, could you provide the steps to apply the fix or the fixed theme?

**Comment by pioug** [comment]
To apply the fix:

- Go to `Sublime Text > Preferences > Browse Packages`. 
- Open `/Theme - Spacegray/Spacegray.sublime-theme`
- Locate this line https://github.com/kkga/spacegray/blob/master/Spacegray.sublime-theme#L807
- Replace `content_margin: 9` by `content_margin: 3`

**Comment by arinsoye** [comment]
Thanks for letting me know. I applied the change you mentioned, albeit differently because I was not able to find .sublime-theme. I am guessing that since this was installed with package control, I have Theme - Spacegray.sublime-package. What I needed to do was to convert that to a .zip, extract the sublime-theme and make the change. Then drop the changed file with a different name under packages.

Finally, I see the fix, however, this time the search bar has a white background. Did you notice that as well?

Anyway really interested in this fix since I am kind of OCD :)

Thanks!

**Comment by marcofugaro** [comment]
Good catch! But that property has effect on the padding of every input field in sublime (say Goto line or Goto File or Quick Switch Project) so that's the thing to consider.

Also I've tried the fix, and found out that actually `7` is the number which correctly aligns the text for me. (Tested with the search bar more squashed possible)
Why instead did you choose `9` @pioug?

Here's how it looks with the fix:
![](http://i.imgur.com/rsclj2B.png)

**Comment by pioug** [comment]
This is how `content_margin: 7` looks for me:
![image](https://cloud.githubusercontent.com/assets/3654180/21054663/81826ed2-be69-11e6-9954-56b62c7553a7.png)

And `content_margin: 9`
![image](https://cloud.githubusercontent.com/assets/3654180/21054736/bc9f462a-be69-11e6-8ef9-b726b9d3fcc9.png)

**Comment by marcofugaro** [comment]
Alright, found out `6` was the right number which aligns the baseline of the text when the search panel is at its lowest height. Thanks for your help, fix out in next patch release
