### ISSUE TITLE
Line Highlighter (Ocean)

### ISSUE THREAD

**Issue by surjithctly** [kkga/spacegray#200]
Any chance to make the Line Highlighter **Color** little more prominent? 

When searching a line through Ctrl + G, I'm having hard time finding the matched line. Its now only a subtle color change, but it should me more prominent.

Is there any way I can edit it myself on my Windows? 

Thanks a lot

~Surjith

**Comment by marcofugaro** [comment]
I am supposing you are using the color scheme `base16-ocean.dark.tmTheme`

To edit the active line color, first install Spacegray manually [as described here](https://github.com/kkga/spacegray#manual), then open the file `base16-ocean.dark.tmTheme` and edit line 40, this one:

https://github.com/kkga/spacegray/blob/d66a32badff46313e8e922e42cd1140439cb3956/base16-ocean.dark.tmTheme#L40

We will not change it as it looks prominent enough, but maybe you can share a screenshot if you think otherwise.
